version: "3.9"

services:
  flaskapp:
    build: flask
    ports:
      - "80:5000"
    volumes:
      - group_data:/app/data
    environment:
      - PORT=5000
      - DBPGIP=postgres
      - RABBITIP=rabbit
      - DBMONGOCONNECT=mongodb://mongo:Lone5864@mongo:27017/
          
  postgres:
    image: "postgres"
    #ports: 
    #  - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'Lone5864'
      POSTGRES_DB: 'groups'
    
  rpc:
    build: rpc
    restart: on-failure
    depends_on:
      - rabbit
    volumes:
      - group_data:/rpc/data
    environment:
      - RABBITIP=rabbit
    
  rabbit:
    image: "rabbitmq"

  mongo: 
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: Lone5864
      MONGO_INITDB_DATABASE: groups

      
volumes:
  group_data: